name: Test and coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.19'
      - name: Run coverage
        run: make test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

  push-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build Images'
        run: |
          docker build -t ghcr.io/${{github.actor}}/authserver:${{github.ref_name}} -f apps/authserver/Dockerfile . 
          docker push ghcr.io/${{github.actor}}/authserver:${{github.ref_name}}
          
          docker build -t ghcr.io/${{github.actor}}/charserver:${{github.ref_name}} -f apps/charserver/Dockerfile . 
          docker push ghcr.io/${{github.actor}}/charserver:${{github.ref_name}}
          
          docker build -t ghcr.io/${{github.actor}}/chatserver:${{github.ref_name}} -f apps/chatserver/Dockerfile . 
          docker push ghcr.io/${{github.actor}}/chatserver:${{github.ref_name}}
          
          docker build -t ghcr.io/${{github.actor}}/game-load-balancer:${{github.ref_name}} -f apps/game-load-balancer/Dockerfile . 
          docker push ghcr.io/${{github.actor}}/game-load-balancer:${{github.ref_name}}
          
          docker build -t ghcr.io/${{github.actor}}/guidserver:${{github.ref_name}} -f apps/guidserver/Dockerfile . 
          docker push ghcr.io/${{github.actor}}/guidserver:${{github.ref_name}}
          
          docker build -t ghcr.io/${{github.actor}}/guildserver:${{github.ref_name}} -f apps/guildserver/Dockerfile . 
          docker push ghcr.io/${{github.actor}}/guildserver:${{github.ref_name}}
          
          docker build -t ghcr.io/${{github.actor}}/mailserver:${{github.ref_name}} -f apps/mailserver/Dockerfile . 
          docker push ghcr.io/${{github.actor}}/mailserver:${{github.ref_name}}
          
          docker build -t ghcr.io/${{github.actor}}/servers-registry:${{github.ref_name}} -f apps/servers-registry/Dockerfile . 
          docker push ghcr.io/${{github.actor}}/servers-registry:${{github.ref_name}}
